config/routes.rb
Calendar::Application.routes.draw do
  get "user/index"

  resources :events do
  resources :items
  end  

  resources :customers
  resources :products
  resources :categories
  devise_for :users  

  root to: 'static_pages#home'

  match '/signup', to: 'users#new'
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  
end

app/models/event.rb
class Event < ActiveRecord::Base
  #attr_accessible :start_at, :end_at, :name, :user_id
  #has_event_calendar
  #belongs_to :user
  attr_accessible  :customer_id, :date_request, :discount, :name, :start_at, :end_at
  validates :customer_id, :presence => true 
  belongs_to :customer
  has_event_calendar
  has_many :items
  
  #accepts_nested_attributes_for :items
  
  def totalquantity
    iTotal = 0
    self.items.each do |i|
      iTotal = iTotal + i.quantity
    end
    totalquantity = iTotal
  end

  def totalprice
    iTotal = 0;
    self.items.each do |i|
      iTotal = iTotal + (i.price * i.quantity)
    end
    totalitem = iTotal
  end
  
  def totaldiscount
    iTotal = 0;
    self.items.each do |i|
      iTotal = iTotal + (i.price * i.quantity)
    end
    iTotal = (iTotal * (100 - self.discount)) / 100
    totaldescuento= iTotal
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
   before_filter :authenticate_user!
def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def show
    @event = Event.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.pdf do
        pdf = EventsPdf.new(@event, view_context)
        send_data pdf.render, filename: 
        "evento_#{@event.created_at.strftime("%d/%m/%Y")}.pdf",
        type: "application/pdf"
      end
    end
  end

  def new
    @event = Event.new
    @event.discount = 0


    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'event was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
    end
  end
end

app/helpers/event_helper.rb
module EventHelper
end

app/views/events/_event.html.erb
<dl class="dl-horizontal">
  <h2><center><%= @event.name %></center></h2>
  <dt>Cliente:</strong></dt>
  <dd><%= @event.customer.name %></dd>
  <dt>Fecha solicitud:</dt>
  <dd><%= @event.date_request.strftime("%d/%m/%Y") %></dd>
  <dt>Fecha pedido:</dt>
  <dd><%= @event.start_at.strftime("%d/%m/%Y") %></dd>
  <dt>Fecha recepción:</dt>
  <dd><%= @event.end_at.strftime("%d/%m/%Y") %></dd>
  <dt>Descuento:</dt>
  <dd><%= Porcentaje(@event.discount) %></dd>  
</dl>

app/views/events/_form.html.erb
<%= form_for @event, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label 'Nombre pedido', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label 'Cliente', :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :customer_id, Customer.all, :id, :name, {:prompt => true} %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label 'Fecha solicitud', :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :date_request, :class => 'date_select', :event => [:day, :month, :year]%>
    </div>
  </div>
  <div class="control-group">
    <%= f.label 'Fecha pedido', :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :start_at, :class => 'date_select', :event => [:day, :month, :year]%>
    </div>
  </div>
  <div class="control-group">
    <%= f.label 'Fecha retorno', :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :end_at, :class => 'date_select', :event => [:day, :month, :year]%>
    </div>
  </div>
  <div class="control-group">
    <%= f.label 'Descuento', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :discount, :class => 'text_field' %>
    </div>
  </div>
  
  <div class="form-actions">
    <%= f.submit 'Guardar', :class => 'btn btn-primary' %>
    <%= link_to 'Cancelar', events_path, :class => 'btn' %>
  </div>
<% end %>

app/views/events/_item_form.html.erb
<%= form_for [@event, @event.items.build], remote: true, :html => { :class => 'form-horizontal' } do |f| %>
	<tr>
		<td><%= f.collection_select(:product_id, Product.all, :id, :name,  { :prompt => true },{:onchange => "buscaPrecio(this)"})  %></td>
		<td><%= f.text_field :quantity, placeholder: 'Cantidad'%></td>
		<td><%= f.text_field :price, placeholder: 'Valor' %></td>
		<td><%= f.submit 'Guardar', :class => 'btn btn-primary'%></td>
		<td></td>
	</tr>
<% end %>

app/views/events/_item_list.html.erb
<% @event.items.each do |a| %>
	<tr>
		<td><%= a.product.name %></td>
		<td><%= a.quantity%></td>
		<td><%= Moneda(a.price) %></td>
		<td><%= Moneda(a.quantity * a.price) %></td>
		<td><%= link_to 'Cancelar', [@event, a], confirm: '¿Confirma eliminar?', method: :delete, remote: true %></td>
	</tr>
<% end %>
<%if @event.items.count > 0 %>
	<tr>
		<td></td>
		<td><%= @event.totalquantity %></td>
		<td><%= Moneda(@event.totalprice) %></td>
		<td><%= Moneda(@event.totaldiscount) %></td>
		<td></td>
	</tr>
<%end%>

app/views/events/edit.html.erb
<br/><br/>
<h1 align="center">Editar pedido</h1>
<%= render :partial => 'form' %>

app/views/events/index.html.erb
<br/><br/>
<h1 align="center">Lista de Pedidos</h1>
<table id="products" class="display">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Cliente</th>
      <th>Fecha solicitud</th>
      <th>Fecha pedido</th>
      <th>Fecha retorno</th>
      <th>Total</th>     
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><center><%= link_to event.name, event_path(event) %></center></td>
        <td><center><%= event.customer.name %></center></td>
        <td><center><%= event.date_request.strftime("%d/%m/%Y") %></center></td>
        <td><center><%= event.start_at.strftime("%d/%m/%Y") %></center></td>
        <td><center><%= event.end_at.strftime("%d/%m/%Y") %></center></td>
        <td><center><%= event.totaldiscount %></td>
        <td><center><%= link_to 'Editar', edit_event_path(event), :class => 'btn btn-mini' %>
        <%= link_to 'Eliminar', event_path(event), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '¿Confirma eliminar?')), :class => 'btn btn-mini btn-danger' %></center></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Agregar', new_event_path, :class => 'btn btn-primary' %>

app/views/events/new.html.erb
<br/><br/>
<h1 align="center">Nuevo pedido</h1>
<%= render :partial => 'form' %>

app/views/events/show.html.erb
<script type="text/javascript">
$(document).ready;


</script>



<br/><br/>

<%= render :partial => @event %>

<table class="table table-striped">
  <thead>
		<caption>Lista de productos</caption>
		<tr>
			<th>Producto</th><th>Cantidad</th><th>Valor</th><th>Total</th><th></th>
		</tr>
  </thead>
	<tbody id='item_listing'>
		<%= render :partial => 'item_list' %>
	</tbody>
	<tbody id='item_form'>
		<%= render :partial => 'item_form' %>
	</tbody>
</table>

<div class="form-actions">
  <%= link_to 'Volver', events_path, :class => 'btn'  %>
  <%= link_to 'Editar', edit_event_path(@event), :class => 'btn' %>
  <%= link_to 'Exportar a PDF', event_path(@event, :format => "pdf"), :class => 'btn' %>
  <%= link_to 'Eliminar', event_path(@event), :method => 'delete', :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '¿Confirma eliminar?')), :class => 'btn btn-danger' %>
  
</div>