config/routes.rb
Calendar::Application.routes.draw do
  get "user/index"

  resources :events do
  resources :items
  end  

  resources :customers
  resources :products
  resources :categories
  devise_for :users  

  root to: 'static_pages#home'

  match '/signup', to: 'users#new'
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :address, :city, :email, :name, :number
  has_many :events
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
 before_filter :authenticate_user!
 def index
    @customers = Customer.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit
    @customer = Customer.find(params[:id])
    
    respond_to do |format|
      format.html # edit.html.erb
    end
  end

  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'customer was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'customer was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
    end
  end  
end

app/views/customers/_form.html.erb
<%= form_for @customer, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label 'Nombre', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label 'Dirección', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label 'Número', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :number, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label 'Ciudad', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :city, :class => 'text_field' %>
    </div>
  </div>  
  <div class="control-group">
    <%= f.label 'Email', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit 'Guardar', :class => 'btn btn-primary' %>
    <%= link_to 'Cancelar', customers_path, :class => 'btn' %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<br/><br/>
<h1 align="center">Editar Cliente</h1>
<%= render :partial => 'form' %>

app/views/customers/index.html.erb
<br/><br/>
<h1>Lista de Clientes</h1>
<table id="products" class="display">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Direccion</th>
      <th>Ciudad</th>
      <th>Email</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><center><%= link_to customer.name, customer_path(customer) %></center></td>
        <td><center><%= customer.address %>, <%= customer.number %></center></td>
        <td><center><%= customer.city %></center></td>
        <td><center><%= customer.email %></center></td>
        <td><center><%= link_to 'Editar', edit_customer_path(customer), :class => 'btn btn-mini' %>
        <%= link_to 'Eliminar', customer_path(customer), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '¿Confirma eliminar?')), :class => 'btn btn-mini btn-danger' %></center></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Agregar', new_customer_path, :class => 'btn btn-primary' %>

app/views/customers/new.html.erb
<br/><br/>
<h1 align="center">Nuevo Cliente</h1>
<%= render :partial => 'form' %>

app/views/customers/show.html.erb
<br/><br/>

<dl class="dl-horizontal">
  <dt>Nombre:</dt>
  <dd><%= @customer.name %></dd>
  <dt>Direccion:</dt>
  <dd><%= @customer.address %></dd>
  <dt>Número:</dt>
  <dd><%= @customer.number %></dd>
  <dt>Ciudad:</dt>
  <dd><%= @customer.city%></dd>
  <dt>Email:</dt>
  <dd><%= @customer.email %></dd>
</dl>

<div class="form-actions">
  <%= link_to 'Volver', customers_path, :class => 'btn'  %>
  <%= link_to 'Editar', edit_customer_path(@customer), :class => 'btn' %>
  <%= link_to 'Eliminar', customer_path(@customer), :method => 'delete', :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '¿Confirma eliminar?')), :class => 'btn btn-danger' %>
</div>