config/routes.rb
Calendar::Application.routes.draw do
  get "user/index"

  resources :events do
  resources :items
  end  

  resources :customers
  resources :products
  resources :categories
  devise_for :users  

  root to: 'static_pages#home'

  match '/signup', to: 'users#new'
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
 before_filter :authenticate_user!
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to categories_url }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
    end
  end
  
end

app/views/categories/_form.html.erb
<%= form_for @category, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label 'Nombre', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit 'Guardar', :class => 'btn btn-primary' %>
    <%= link_to 'Cancelar',
                categories_path, :class => 'btn' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<br/><br/>
<h1 align="center">Editar Categoria</h1>
<%= render :partial => 'form' %>

app/views/categories/index.html.erb
<br/><br/>
<h1 align="center">Categorias</h1>
<table id="products" class="display">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><center><%= link_to category.name, category_path(category) %></center></td>

        <td><center><%= link_to 'Editar', edit_category_path(category), :class => 'btn btn-mini' %>
        <%= link_to 'Eliminar', category_path(category), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '¿Confirma eliminar?')), :class => 'btn btn-mini btn-danger' %></center></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Agregar', new_category_path, :class => 'btn btn-primary' %>

app/views/categories/new.html.erb
<br/><br/>
<h1 align="center">Nueva categoria</h1>
<%= render :partial => 'form' %>

app/views/categories/show.html.erb
<br/><br/>

<dl class="dl-horizontal">
  <dt>Nombre:</dt>
  <dd><%= @category.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to 'Volver', categories_path, :class => 'btn'  %>
  <%= link_to 'Editar', edit_category_path(@category), :class => 'btn' %>
  <%= link_to 'Eliminar', category_path(@category), :method => 'delete', :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '¿Confirma eliminar?')), :class => 'btn btn-danger' %>
</div>