config/routes.rb
Calendar::Application.routes.draw do
  get "user/index"

  resources :events do
  resources :items
  end  

  resources :customers
  resources :products
  resources :categories
  devise_for :users  

  root to: 'static_pages#home'

  match '/signup', to: 'users#new'
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>Proyecto de tecnologías webs - Universidad de Talca - Facultad de ingenieria</small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <% if user_signed_in? %>
	  
	  <li><%= link_to "Clientes", customers_path %></li>
	  <li><%= link_to "Categorias", categories_path %></li>
          <li><%= link_to "Productos", products_path %></li>
          <li><%= link_to "Pedidos", events_path %></li>
          <li><%= link_to "Agenda", calendar_path %></li>
          	<li style="padding: 10px 15px;">Ingresaste como: <%= current_user.email %>
          	<li><%= link_to "Salir", destroy_user_session_path, :method => :delete %></li>
          <% else %>
          <li><%= link_to "Ingresar", new_user_session_path %></li>
          <%end%>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Orden de pedidos</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header'%>
    <% if flash[:notice] %>
    	<div class="notice"><%= flash[:notice] %></div>
  	<% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
  <%= render 'layouts/footer'%>
</html>